# Generated by Django 2.0.5 on 2018-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='work',
            name='material',
            field=models.CharField(max_length=256),
        ),
    ]
