# Generated by Django 2.1 on 2018-08-29 18:43

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180622_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/placeholders/no-image.jpg', upload_to=gallery.models.image_upload_handler)),
                ('dimensions_x', models.IntegerField()),
                ('dimensions_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('videoId', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
