# Generated by Django 2.1 on 2018-08-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180829_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
    ]
