# Generated by Django 2.0.6 on 2018-09-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20180829_2131'),
        ('gallery', '0003_auto_20180623_0907'),
    ]

    operations = [
    ]
