# Generated by Django 2.1 on 2018-09-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_merge_20180901_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
