# Generated by Django 2.1 on 2018-11-18 09:21

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_collection_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='photography',
            name='image',
            field=models.ImageField(default='placeholders/no-image.jpg', upload_to=gallery.models.photo_upload_handler),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(default='placeholders/no-image.jpg', upload_to=gallery.models.image_upload_handler),
        ),
    ]
